name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Clean Docker disk space
        run: |
          sudo docker system prune -a --volumes --force
          sudo docker builder prune --all --force
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          sudo truncate -s 0 /var/log/*.log || true
          sudo yum clean all
          sudo rm -rf /var/cache/yum
        shell: bash

      - name: Build Docker image
        run: |
          sudo docker build -t flightticket --progress=plain .
        shell: bash

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Clean Docker disk space
        run: |
          sudo docker system prune -a --volumes --force
          sudo docker builder prune --all --force
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          sudo truncate -s 0 /var/log/*.log || true
          sudo yum clean all
          sudo rm -rf /var/cache/yum
        shell: bash

      - name: Deploy Docker Compose
        run: |
          cd /home/ec2-user/flightTicketApp
          sudo docker compose down
          sudo docker compose up -d --build
        shell: bash
